# Generated by Django 3.2.8 on 2022-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_blog_publish_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Area of Expertise(For doctor user only)'),
        ),
    ]
