# Generated by Django 3.2.8 on 2022-05-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
