# Generated by Django 3.2.8 on 2022-05-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_patient_user_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post',
        ),
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
